travis:
  secure:
    BINSTAR_TOKEN: E5jlLZMO3tI/JVNdsZOxa0Ad2VtOpH3KpMej9Ah0E6rof+mjqeFNTG3dRWVI1HqgWV0FShZV8pt+VNDS68l724ibG6ek94QaG9IIGmK96BBpuIGHkR7ecOhhkvlb67o0k6t4wFHN1TYWFXU4F7Y4CW6ChcYcvS7RYjvxZpcZrPAdSRQYhyxZzcXKO8gudWBEU12GFguJFFJA9EZbV9awMCawIDQnonKDpS3iUDaQuLLJtsZUX/MuBzSxBDSvPJgBatg1WqDKD93l9dlvVYlYw9kCN1d7MN/LyfbxsNqoCOkYVEgVkhijWjz0OUVpr0Uy2ck051k16+niwKmiGzJ8Pcx/YgB7uCfRV7yLlUlFI4XW7jp43eVpVR1fk81QF6laJepZTwlR/BpL1X4q7ogIy7BlVFgKe83w8Oe+0j74/UFCEZbV6PZSVk2e/4h9PdV/dMUOYx1/4y4ozZUrh9jE8w6Ik2dtKuDvz2JvtlA1fqNW9JswKr5e2bj0uJxFDHuhRyF+D6j2Gd5jtWglp7BA1TnfuXYdmqUoMUfHW82XukJvDjwA6e9RxMObrGJYDcsOOJ/2PFkOZ36Ul53cmoPZOY4TU6GQmww/aXDncot1aTEBCGqG9wN6LJPBnbARv0jVJVFi8cRjGO7Il3NtXYwMcgsqRlNI4uy7dOq175DUvDI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
